/******************************************************************************/
/****         Generated by IBExpert                                        ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES UTF8;


/******************************************************************************/
/****                           Stored functions                           ****/
/******************************************************************************/



SET TERM ^ ;

CREATE OR ALTER FUNCTION GET_WORD_NUM (
    P_STRING VARCHAR(4096),
    P_SPLITTER CHAR(1),
    WORD_NUM INTEGER)
RETURNS VARCHAR(4096) DETERMINISTIC
AS
BEGIN
  RETURN NULL;
END^


SET TERM ; ^

/******************************************************************************/
/****                           Stored functions                           ****/
/******************************************************************************/



SET TERM ^ ;

ALTER FUNCTION GET_WORD_NUM (
    P_STRING VARCHAR(4096),
    P_SPLITTER CHAR(1),
    WORD_NUM INTEGER)
RETURNS VARCHAR(4096) DETERMINISTIC
AS
declare variable LASTPOS integer;
declare variable NEXTPOS integer;
declare variable CNT integer;
declare variable PART varchar(4096);
begin
  if (:WORD_NUM <= 0) then
   return NULL;
  if (OCTET_LENGTH(:P_STRING) = 0) then
   return NULL;
  CNT = 0;
  PART = '';
    P_STRING = :P_STRING || :P_SPLITTER;
    LASTPOS = 1;
    NEXTPOS = position(:P_SPLITTER, :P_STRING, LASTPOS);
    if (LASTPOS = NEXTPOS) then
        begin
            PART = substring(:P_STRING from :LASTPOS for :NEXTPOS - :LASTPOS);
            CNT = CNT + 1;
            LASTPOS = :NEXTPOS + 1;
            NEXTPOS = position(:P_SPLITTER, :P_STRING, LASTPOS);

            if (:WORD_NUM = CNT) then
             return PART;
        end
    while (:NEXTPOS > 1) do
        begin
            PART = substring(:P_STRING from :LASTPOS for :NEXTPOS - :LASTPOS);
            LASTPOS = :NEXTPOS + 1;
            NEXTPOS = position(:P_SPLITTER, :P_STRING, LASTPOS);
            CNT = CNT + 1;
            if (:WORD_NUM = CNT) then
             return PART;
        end
    if (CNT < ABS(:WORD_NUM)) then
     return NULL;
end^




SET TERM ; ^

