/******************************************************************************/
/****         Generated by IBExpert                                        ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES UTF8;

/******************************************************************************/
/****                           Stored functions                           ****/
/******************************************************************************/



SET TERM ^ ;

CREATE OR ALTER FUNCTION COUNT_OF_WORDS (
    P_STRING VARCHAR(4096),
    P_SPLITTER CHAR(1))
RETURNS INTEGER DETERMINISTIC
AS
BEGIN
  RETURN NULL;
END^







SET TERM ; ^



/******************************************************************************/
/****                           Stored functions                           ****/
/******************************************************************************/



SET TERM ^ ;

create or alter function COUNT_OF_WORDS (
    P_STRING varchar(4096),
    P_SPLITTER char(1))
returns integer deterministic
as
declare variable LASTPOS integer;
declare variable NEXTPOS integer;
declare variable CNT integer;
begin
if (CHAR_LENGTH(:P_STRING) = 0) then
  return 0;
  CNT = 0;
  LASTPOS = 1;
  NEXTPOS = position(:P_SPLITTER, :P_STRING, LASTPOS);
  if (LASTPOS = NEXTPOS) then
        begin
            CNT = CNT + 1;
            LASTPOS = :NEXTPOS + 1;
            NEXTPOS = position(:P_SPLITTER, :P_STRING, LASTPOS);
        end
  while (:NEXTPOS > 1) do
        begin
            LASTPOS = :NEXTPOS + 1;
            NEXTPOS = position(:P_SPLITTER, :P_STRING, LASTPOS);
            CNT = CNT + 1;
        end
 if (CNT > 0) then
  return CNT + 1; else
  return 0;

end^




SET TERM ; ^



